lizards-and-pumpkins/catalog

src/Http/ContentDelivery/FrontendFactory.php
src/Http/ContentDelivery/PageBuilder/SnippetTransformation/ProductJsonSnippetTransformation.php
src/Http/ContentDelivery/ProductJsonService/EnrichProductJsonWithPrices.php
src/Http/ContentDelivery/ProductJsonService/ProductJsonService.php
src/ProductListing/ContentDelivery/ProductListingPageContentBuilder.php
src/ProductRelations/ContentDelivery/ProductRelationsApiV1GetRequestHandler.php
src/ProductRelations/ContentDelivery/ProductRelationsService.php
src/ProductRelations/ContentDelivery/SameSeriesProductRelations.php
src/ProductRelations/ProductRelations.php
src/ProductRelations/ProductRelationsFactory.php
src/Util/Factory/CommonFactory.php
tests/Integration/Suites/RelatedModelsProductRelationsApiTest.php
tests/Integration/Util/AbstractIntegrationTest.php
tests/Unit/Suites/Http/ContentDelivery/FrontendFactoryTest.php
tests/Unit/Suites/Http/ContentDelivery/PageBuilder/SnippetTransformation/ProductJsonSnippetTransformationTest.php
tests/Unit/Suites/Http/ContentDelivery/ProductJsonService/EnrichProductJsonWithPricesTest.php
tests/Unit/Suites/Http/ContentDelivery/ProductJsonService/ProductJsonServiceTest.php
tests/Unit/Suites/Import/Price/PriceSnippetRendererTest.php
tests/Unit/Suites/ProductRelations/ContentDelivery/ProductRelationsApiV1GetRequestHandlerTest.php
tests/Unit/Suites/ProductRelations/ContentDelivery/ProductRelationsServiceTest.php
tests/Unit/Suites/ProductRelations/ContentDelivery/SameSeriesProductRelationsTest.php
tests/Unit/Suites/Util/Factory/CommonFactoryTest.php

Issue #947: Decouple ProductRelationsFactory from FrontendFactory

---

README.md

Issue: #942: Add README

---

src/Context/Website/ConfigurableUrlToWebsiteMap.php

Issue: #945: Rename LP_WEBSITE_MAP to LP_BASE_URL_TO_WEBSITE_MAP

---

src/Context/BaseUrl/WebsiteBaseUrlBuilder.php
src/RestApi/ApiRouter.php
src/RestApi/RestApiFactory.php
src/Util/Config/ConfigReader.php
src/Util/Config/EnvironmentConfigReader.php
src/Util/Config/Exception/EnvironmentConfigKeyIsNotSetException.php
src/Util/Factory/CommonFactory.php
tests/Integration/phpunit.xml.dist
tests/Unit/Suites/Context/BaseUrl/WebsiteBaseUrlBuilderTest.php
tests/Unit/Suites/Util/Config/EnvironmentConfigReaderTest.php
tests/Unit/phpunit.xml.dist

Issue #966: Throw an exception if environment variable is not set

---

src/Import/CatalogListingImportCallbackFailureMessage.php
src/Import/FileStorage/FileContent.php
src/Logging/LoggingCommandHandlerFactory.php
src/Logging/LoggingDomainEventHandlerFactory.php
src/Messaging/Command/CommandHandlerFactory.php
src/Messaging/Command/Exception/InvalidCommandConsumerPidException.php
src/Messaging/Command/Exception/NoShutdownWorkerCommandMessageException.php
src/Messaging/Command/Exception/NotShutdownWorkerCommandMessageException.php
src/Messaging/Command/ShutdownWorkerCommand.php
src/Messaging/Command/ShutdownWorkerCommandHandler.php
src/Messaging/Event/DomainEventHandlerFactory.php
src/Messaging/Event/Exception/InvalidDomainEventConsumerPidException.php
src/Messaging/Event/Exception/NoShutdownWorkerDomainEventMessageException.php
src/Messaging/Event/ShutdownWorkerDomainEvent.php
src/Messaging/Event/ShutdownWorkerDomainEventHandler.php
src/Util/Factory/CommonFactory.php
src/Util/functions.php
tests/Unit/Suites/Logging/LoggingCommandHandlerFactoryTest.php
tests/Unit/Suites/Logging/LoggingDomainEventHandlerFactoryTest.php
tests/Unit/Suites/Messaging/Command/ShutdownWorkerCommandHandlerTest.php
tests/Unit/Suites/Messaging/Command/ShutdownWorkerCommandTest.php
tests/Unit/Suites/Messaging/Event/DomainEventHandlerLocatorTest.php
tests/Unit/Suites/Messaging/Event/ShutdownWorkerDomainEventHandlerTest.php
tests/Unit/Suites/Messaging/Event/ShutdownWorkerDomainEventTest.php
tests/Unit/Suites/Util/Factory/CommonFactoryTest.php

This PR is ready to be merged, just be aware that the CLI commands to add them to the queues are not part of a separate PR.

Add ShutdownWorker command and domain event

---

src/Messaging/Consumer/ConsumerShutdownRequestedLogMessage.php
src/Messaging/Consumer/ShutdownWorkerDirective.php
src/Messaging/Consumer/ShutdownWorkerDirectiveHandler.php
src/Util/Factory/CommonFactory.php
tests/Unit/Suites/Messaging/Consumer/ConsumerShutdownRequestedLogMessageTest.php
tests/Unit/Suites/Messaging/Consumer/ShutdownWorkerDirectiveHandlerTest.php

Add some transparency what is going on.
Closes #969

Log command and event consumer shutdown directive processing

---

src/Messaging/Command/CommandConsumer.php
src/Messaging/Event/DomainEventConsumer.php
src/Messaging/QueueMessageConsumer.php
tests/Unit/Suites/Messaging/Command/CommandConsumerTest.php
tests/Unit/Suites/Messaging/Event/DomainEventConsumerTest.php

Provide method to process exactly the number of messages on the queue to avoid blocking

---

src/DataPool/CurrentDataVersion.php
src/DataPool/DataPoolReader.php
src/DataPool/DataPoolWriter.php
src/Import/CatalogImport.php
src/Import/CatalogImportWasTriggeredDomainEventHandler.php
tests/Integration/Suites/EdgeToEdgeImportCatalogTest.php
tests/Integration/Util/AbstractIntegrationTest.php
tests/Unit/Suites/DataPool/DataPoolWriterTest.php
tests/Unit/Suites/Http/ContentDelivery/FrontendFactoryTest.php
tests/Unit/Suites/Import/CatalogImportTest.php
tests/Unit/Suites/Import/CatalogImportWasTriggeredDomainEventHandlerTest.php
tests/Unit/Suites/ProductRelations/ProductRelationsFactoryTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchFactoryTest.php
tests/shared-fixture/simple_product-v1.xml
tests/shared-fixture/simple_product-v2.xml

Also add better integration test coverage for data versioned projection.
Closes #984

Use supplied data version during projection.

---

src/DataPool/CurrentDataVersion.php
src/DataPool/DataPoolReader.php
src/DataPool/DataVersion/RestApi/CurrentVersionApiV1GetRequestHandler.php
src/RestApi/RestApiFactory.php
tests/Integration/Suites/CurrentVersionApiTest.php
tests/Unit/Suites/DataPool/DataPoolReaderTest.php
tests/Unit/Suites/DataPool/DataVersion/RestApi/CurrentVersionApiV1GetRequestHandlerTest.php
tests/Unit/Suites/Http/ContentDelivery/FrontendFactoryTest.php
tests/Unit/Suites/ProductRelations/ProductRelationsFactoryTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchFactoryTest.php
tests/Unit/Suites/RestApi/RestApiFactoryTest.php

This is only the first (smaller) part of the full issue. The PUT request handler and processing have yet to be implemented.

Issue #988: Add GET endpoint for the current_version API

---

src/Import/RootTemplate/Import/Exception/InvalidTemplateApiRequestBodyException.php
src/Import/RootTemplate/Import/TemplatesApiV1PutRequestHandler.php
src/Import/RootTemplate/Import/TemplatesApiV2PutRequestHandler.php
src/ProductRelations/ProductRelationsFactory.php
src/ProductSearch/ContentDelivery/ProductSearchFactory.php
src/RestApi/ApiRequestHandlerLocator.php
src/RestApi/RestApiFactory.php
src/Util/Factory/SampleMasterFactory.php
tests/Integration/Suites/ProductListingTemplateProjectionTest.php
tests/Unit/Suites/Http/ContentDelivery/FrontendFactoryTest.php
tests/Unit/Suites/Import/RootTemplate/Import/TemplatesApiV1PutRequestHandlerTest.php
tests/Unit/Suites/Import/RootTemplate/Import/TemplatesApiV2PutRequestHandlerTest.php
tests/Unit/Suites/ProductRelations/ProductRelationsFactoryTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchFactoryTest.php
tests/Unit/Suites/RestApi/ApiRequestHandlerLocatorTest.php
tests/Unit/Suites/RestApi/RestApiFactoryTest.php

Please do not yet close the issue. I still have to check the other projectors to be sure, especially the search projector and content block projector.

Issue #991: Use correct data version during projections.

---

src/Import/ContentBlock/ContentBlockSnippetRenderer.php
src/Import/ContentBlock/ContentBlockSource.php
src/Import/ContentBlock/RestApi/ContentBlocksApiV1PutRequestHandler.php
src/ProductListing/Import/ProductSearchResultMetaSnippetRenderer.php
src/RestApi/RestApiFactory.php
tests/Integration/Suites/ProductDetailViewSnippetsTest.php
tests/Integration/Suites/ProductUrlKeyStoreTest.php
tests/Unit/Suites/Import/ContentBlock/ContentBlockSnippetRendererTest.php
tests/Unit/Suites/Import/ContentBlock/ContentBlockSourceTest.php
tests/Unit/Suites/Import/ContentBlock/ContentBlockWasUpdatedDomainEventHandlerTest.php
tests/Unit/Suites/Import/ContentBlock/ContentBlockWasUpdatedDomainEventTest.php
tests/Unit/Suites/Import/ContentBlock/RestApi/ContentBlocksApiV1PutRequestHandlerTest.php
tests/Unit/Suites/Import/ContentBlock/UpdateContentBlockCommandHandlerTest.php
tests/Unit/Suites/Import/ContentBlock/UpdateContentBlockCommandTest.php
tests/Unit/Suites/Import/RootTemplate/Import/TemplatesApiV1PutRequestHandlerTest.php
tests/Unit/Suites/Logging/LoggingCommandHandlerFactoryTest.php
tests/Unit/Suites/Logging/LoggingDomainEventHandlerFactoryTest.php
tests/Unit/Suites/RestApi/RestApiFactoryTest.php
tests/Unit/Suites/Util/Factory/CommonFactoryTest.php

This is a preparatory refactoring to add a content block api data_version parameter.

Issue #991: Add context with DataVersion to ContentBlockSource

---

src/ProductSearch/Import/DefaultAttributeValueCollector.php
tests/Unit/Suites/ProductSearch/Import/DefaultAttributeValueCollectorTest.php

Issue: #1001: Consider special price not set if value is an empty string

---

src/Logging/LoggingCommandHandlerFactory.php
src/Logging/LoggingDomainEventHandlerFactory.php
src/Logging/LoggingQueueFactory.php
tests/Unit/Suites/Logging/LoggingCommandHandlerFactoryTest.php
tests/Unit/Suites/Logging/LoggingDomainEventHandlerFactoryTest.php
tests/Unit/Suites/Logging/LoggingQueueFactoryTest.php

**NOTE:** Please merge this PR after https://github.com/lizards-and-pumpkins/catalog/pull/1011
I'm just opening this one already so it can be reviewed because I'm traveling this evening and will not be able to push this one as soon as #1011 is merged.

1010 refactor logging factories deps

---

src/Logging/LoggingCommandHandlerFactory.php
src/Logging/LoggingDomainEventHandlerFactory.php
src/Util/Factory/CommonFactory.php
tests/Unit/Suites/Util/Factory/CommonFactoryTest.php

Small follow up refactoring.
Closes #1010

Move logging decorator factory method from common factory into the logging factories

---

src/Http/ContentDelivery/FrontendFactory.php
src/ProductListing/ContentDelivery/ProductSearchRequestHandler.php
src/ProductSearch/ContentDelivery/DefaultFullTextCriteriaBuilder.php
src/ProductSearch/ContentDelivery/Exception/EmptyQueryStringException.php
src/ProductSearch/ContentDelivery/FullTextCriteriaBuilder.php
src/ProductSearch/ContentDelivery/ProductSearchApiV1GetRequestHandler.php
src/ProductSearch/ContentDelivery/ProductSearchFactory.php
tests/Unit/Suites/ProductListing/ContentDelivery/ProductSearchRequestHandlerTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/DefaultFullTextCriteriaBuilderTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchApiV1GetRequestHandlerTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchFactoryTest.php

Issue #1014: Fix multi-word search for product search page

---

src/Util/Factory/FactoryTrait.php
src/Util/Factory/FactoryWithCallback.php
src/Util/Factory/MasterFactoryTrait.php

Issue #1024: Add beforeFactoryRegistrationCallback

---

src/DefaultWebFront.php

Issue #1028: Register ProductSearchFactory in DefaultWebFront

---

src/ProductRelations/ProductRelationsFactory.php
src/ProductSearch/ContentDelivery/ProductSearchFactory.php
src/Util/Factory/FactoryCallbackTrait.php
src/Util/Factory/FactoryTrait.php
src/Util/Factory/FactoryWithCallback.php
src/Util/Factory/FactoryWithCallbackTrait.php
src/Util/Factory/MasterFactoryTrait.php
tests/Unit/Suites/ConsoleCommand/CliBootstrapTest.php
tests/Unit/Suites/ConsoleCommand/CliFactoryBootstrapTest.php
tests/Unit/Suites/Http/ContentDelivery/FrontendFactoryTest.php
tests/Unit/Suites/ProductRelations/ProductRelationsFactoryTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/ProductSearchFactoryTest.php
tests/Unit/Suites/Util/Factory/CatalogMasterFactoryTest.php
tests/Unit/Suites/Util/Factory/FactoryTraitTest.php
tests/Unit/Suites/Util/Factory/FactoryWithCallbackTraitTest.php

Issue #1024: Clean up factory callback implementation

---

bin/consumerSupervisor.sh
bin/interactive-consumer-ui.sh
bin/manage-consumer.sh

Issue #998: Migrate CLI commands

---

src/ConsoleCommand/Command/ImportCatalogConsoleCommand.php
src/ConsoleCommand/Command/ImportContentBlockConsoleCommand.php
src/ConsoleCommand/Command/ImportTemplateConsoleCommand.php
tests/Unit/Suites/ConsoleCommand/Command/ImportCatalogConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ImportContentBlockConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ImportTemplateConsoleCommandTest.php

Issue #1033: Add dataVersion to CLI commands that trigger imports

---

src/ConsoleCommand/Command/DataversionGetConsoleCommand.php
src/ConsoleCommand/Command/DataversionSetConsoleCommand.php
tests/Unit/Suites/ConsoleCommand/Command/DataversionGetConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/DataversionSetConsoleCommandTest.php

Issue #1020: Add CLI command to set and get data the current data version

---

src/Context/DataVersion/ContextVersion.php
src/Import/RestApi/CatalogImportApiV1PutRequestHandler.php
src/Import/RestApi/CatalogImportApiV2PutRequestHandler.php
src/RestApi/RestApiFactory.php
tests/Unit/Suites/Context/DataVersion/ContextVersionTest.php
tests/Unit/Suites/Import/RestApi/CatalogImportApiV1PutRequestHandlerTest.php
tests/Unit/Suites/Import/RestApi/CatalogImportApiV2PutRequestHandlerTest.php

Issue #1048: Take data version from request param if present.

---

src/Http/HttpConnectRequest.php
src/Http/HttpDeleteRequest.php
src/Http/HttpGetRequest.php
src/Http/HttpHeaders.php
src/Http/HttpOptionsRequest.php
src/Http/HttpPostRequest.php
src/Http/HttpPutRequest.php
src/Http/HttpRequest.php
src/Http/HttpRequestBody.php
src/Http/HttpResponse.php
src/Http/HttpTraceRequest.php
src/Http/HttpUrl.php
tests/Unit/Suites/Http/HttpConnectRequestTest.php
tests/Unit/Suites/Http/HttpDeleteRequestTest.php
tests/Unit/Suites/Http/HttpGetRequestTest.php
tests/Unit/Suites/Http/HttpHeadersTest.php
tests/Unit/Suites/Http/HttpOptionsRequestTest.php
tests/Unit/Suites/Http/HttpTraceRequestTest.php
tests/Unit/Suites/Http/HttpUrlTest.php

Issue #1063: Add missing HTTP 1.1 request methods

---

src/Import/ImageStorage/ImageProcessing/ImageProcessor.php

Issue #1071: Fix race condition while creating directory

---

src/Import/SnippetContainer.php
src/ProductDetail/ProductDetailPageMetaInfoSnippetContent.php
src/ProductListing/Import/ProductListingSnippetContent.php
tests/Unit/Suites/Import/SnippetContainerTest.php
tests/Unit/Suites/ProductListing/Import/ProductListingSnippetContentTest.php

Issue #1073: Drop unused getters

---

src/Util/Factory/Exception/FactoryAlreadyRegisteredException.php
src/Util/Factory/MasterFactoryTrait.php
tests/Integration/Suites/ConsoleCommand/ImportCatalogConsoleCommandIntegrationTest.php
tests/Integration/Util/AbstractIntegrationTest.php
tests/Integration/Util/IntegrationTestFactory.php
tests/Integration/Util/TestDataPoolQuery.php
tests/Unit/Suites/ConsoleCommand/CliFactoryBootstrapTest.php
tests/Unit/Suites/Util/Factory/CatalogMasterFactoryTest.php

Issue #1059: Check factory only registered once

---

src/Import/PageMetaInfoSnippetContent.php
src/ProductDetail/ProductDetailMetaSnippetRenderer.php
src/ProductDetail/ProductDetailPageMetaInfoSnippetContent.php
src/ProductListing/ContentDelivery/ProductSearchResultMetaSnippetContent.php
src/ProductListing/Import/ProductListingSnippetContent.php
src/ProductListing/Import/ProductListingSnippetRenderer.php
src/ProductListing/Import/ProductSearchResultMetaSnippetRenderer.php
tests/Integration/Suites/FrontendRenderingTest.php
tests/Unit/Suites/ProductDetail/ProductDetailPageMetaInfoSnippetContentTest.php
tests/Unit/Suites/ProductDetail/ProductDetailViewRequestHandlerTest.php
tests/Unit/Suites/ProductListing/ContentDelivery/ProductListingRequestHandlerTest.php
tests/Unit/Suites/ProductListing/ContentDelivery/ProductSearchRequestHandlerTest.php
tests/Unit/Suites/ProductListing/ContentDelivery/ProductSearchResultMetaSnippetContentTest.php
tests/Unit/Suites/ProductListing/Import/ProductListingSnippetContentTest.php
tests/Unit/Suites/ProductListing/Import/ProductSearchResultMetaSnippetRendererTest.php

Issue #1073: Allow arbitrary data in product detail meta snippet

---

src/DataPool/UrlKeyStore/FileUrlKeyStore.php
src/DataPool/UrlKeyStore/InMemoryUrlKeyStore.php
src/DataPool/UrlKeyStore/IntegrationTestUrlKeyStoreAbstract.php
tests/Unit/Suites/DataPool/UrlKeyStore/AbstractIntegrationTestUrlKeyStoreTest.php

Issue #972: Allow empty url key in search engine

---

src/Http/ContentDelivery/ProductJsonService/Exception/ProductSnippetNotFoundInKeyValueStorageException.php
src/Http/ContentDelivery/ProductJsonService/Exception/SnippetNotFoundException.php
src/Http/ContentDelivery/ProductJsonService/ProductJsonService.php
tests/Unit/Suites/Http/ContentDelivery/ProductJsonService/ProductJsonServiceTest.php

Issue #1042: Throw Exception if snippet not found in key value storage

---

src/Import/RestApi/TemplateApiV1GetRequestHandler.php
src/RestApi/RestApiFactory.php
swagger/management-api.yaml
tests/Integration/Suites/TemplateListApiTest.php
tests/Unit/Suites/Import/RestApi/TemplateApiV1GetRequestHandlerTest.php
tests/Unit/Suites/RestApi/RestApiFactoryTest.php

Issue #1036: Templates GET api endpoint

---

src/Context/BaseUrl/HttpBaseUrl.php
tests/Unit/Suites/Context/BaseUrl/HttpBaseUrlTest.php

#1090: Fix base URL validation

---

composer.json
tests/Integration/phpunit.xml.dist
tests/Unit/Suites/ConsoleCommand/BaseCliCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ConsumeEventsConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ImportCatalogConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ImportContentBlockConsoleCommandTest.php
tests/Unit/Suites/ConsoleCommand/Command/ImportTemplateConsoleCommandTest.php
tests/Unit/Suites/Messaging/Command/CommandQueueTest.php
tests/Unit/Suites/Messaging/Event/DomainEventQueueTest.php
tests/Unit/Suites/ProductDetail/ProductDetailViewRequestHandlerTest.php
tests/Unit/Suites/ProductListing/ContentDelivery/ProductListingPageContentBuilderTest.php
tests/Unit/Util/UnitTestFactory.php
tests/Unit/phpunit.xml.dist

#1094: Upgrade to PHPUnit 6.x

---

tests/shared-fixture/catalog.xml

#1097: Make shared catalog fixture sample project compatible

---

src/Import/RestApi/CatalogImportApiV2PutRequestHandler.php
src/Import/RestApi/Exception/InvalidDataVersionTypeException.php
tests/Unit/Suites/Import/RestApi/CatalogImportApiV2PutRequestHandlerTest.php

#1092: Allow integers and doubled as data version input

---

src/ContentBlock/ContentDelivery/ContentBlockApiV2GetRequestHandler.php
src/ContentBlock/ContentDelivery/ContentBlockService.php
src/ContentBlock/ContentDelivery/ContentBlockServiceFactory.php
src/ContentBlock/ContentDelivery/Exception/ContentBlockNotFoundException.php
src/ContentBlock/ContentDelivery/Exception/UnableToProcessContentBlockApiGetRequestException.php
src/RestApiWebFront.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockApiV2GetRequestHandlerTest.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockServiceFactoryTest.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockServiceTest.php
tests/Unit/Suites/RestApiWebFrontTest.php

This api endpoint allows the usage of content blocks with variable content over the api

Added api endpoint to get content blocks

---

src/ContentBlock/ContentDelivery/ContentBlockApiV2GetRequestHandler.php
src/ContentBlock/ContentDelivery/ContentBlockService.php
src/ContentBlock/ContentDelivery/ContentBlockServiceFactory.php
src/ContentBlock/ContentDelivery/Exception/ContentBlockNotFoundException.php
src/ContentBlock/ContentDelivery/Exception/UnableToProcessContentBlockApiGetRequestException.php
tests/Integration/Suites/ContentBlockApiTest.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockApiV2GetRequestHandlerTest.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockServiceFactoryTest.php
tests/Unit/Suites/ContentBlock/ContentDelivery/ContentBlockServiceTest.php

#1103: Improve content block GET API endpoint

---

composer.json
src/ProductSearch/ContentDelivery/DefaultCriteriaParser.php
tests/Integration/Suites/ProductSearchApiTest.php
tests/Unit/Suites/ProductSearch/ContentDelivery/DefaultCriteriaParserTest.php

#1107: Whitespace in search criteria

---

src/Http/HttpUrl.php

#1112: Fix PHP 7.2 INTL_IDNA_VARIANT_2003 deprecation notice
